server:
  # ??????
  port: 8083
  servlet:
    # ???????
    context-path: /dilidili

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    # ????
    name: dilidili
  profiles:
    # ????
    active: dev
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10000MB # 单个上传⽂件⼤⼩限定
      max-request-size: 100000MB # 单次上传⽂件⼤⼩限定

# ?????????
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml # 适配 XML 映射文件
  type-aliases-package: com.he.dilidili.model.entity # 扫描实体类包
  configuration:
    # ???????
    map-underscore-to-camel-case: false
    cache-enabled: false
    # ????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      refresh-mapper: true  # 启用 Mapper 自动刷新

# ????????
logging:
  # ??????
  config: classpath:log/logback-spring.xml

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      # ?? controller ?????????
      packages-to-scan: com.he.dilidili.controller

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
  basic:
    enable: true
    username: admin
    password: 123456

auth:
  login_urls:
    - /auth/out
    - /individual/*
  valid_urls:
    - /a


# ??? OSS ????????
aliyun:
  oss:
    # oss ?????????
    endpoint: oss-cn-nanjing.aliyuncs.com
    # ?????????????
    accessKeyId: LTAI5tQ264G7BjAej4z1Ht2A
    # ???????????? oss ????????????
    accessKeySecret: nbhMbEIpBBmC9vzUTZWUQRAbiiOdu5
    # oss??????
    bucketName: xiaohexiansheng
# 添加以下阿里云短信服务配置
  sms:
    accessKeyId: LTAI5tQ264G7BjAej4z1Ht2A
    accessKeySecret: nbhMbEIpBBmC9vzUTZWUQRAbiiOdu5
    regionId: ap-southeast-1
    signName: 资源分享平台
    templateCode: SMS_154950909

# ?????????????? AccessKey ID
#
#
#AccessKey Secret
#
share:
  sms:
    ccp:
      serverIp: app.cloopen.com
      port: 8883
      accountSId: 2c94811c93863e4f01938abc945a00e2
      accountToken: baf4abfb77874086aa54edb0cdc6986f
      appId: 2c94811c93863e4f01938abc960e00e9
      templateId: 1